FTCPlanner:
  max_x_vel: 2
  max_rotation_vel: 2
  min_rotation_vel: 0.2
  acceleration_x: 1
  acceleration_z: 1
  position_accuracy: 0.2
  rotation_accuracy: 0.03
  slow_down_factor: 2
  sim_time: 2
  local_planner_frequence: 3
  join_obstacle: false
  holonomic_robot: false