# static_map - True if using existing map

global_costmap:
  global_frame: map
  robot_base_frame: base_link
  
  update_frequency: 3.0
  publish_frequency: 3
  resolution: 0.05
  static_map: false
  rolling_window: true
  width: 200.0
  height: 200.0
  transform_tolerance: 0.5

global_costmap/obstacle_layer:
  #No local, prehaps temporary, obstacles should be influence the global costmap.
  enabled: true

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
