arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - base
     - boom
     - stick
     - bucket


  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      base: {trajectory: 0.1, goal: 0.1}
      boom: {trajectory: 0.1, goal: 0.1}
      stick: {trajectory: 0.1, goal: 0.1}
      bucket: {trajectory: 0.1, goal: 0.1}

  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - base
     - boom
     - stick
     - bucket
