velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['left_1', 'left_2',  ]
  right_wheel: [ 'right_1', 'right_2', ]
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false
  publish_cmd: true
  allow_multiple_cmd_vel_publishers: true 
  base_frame_id: "car_body"
  # Wheel separation and radius multipliers
  # wheel_separation_multiplier: 1.5 # default: 1.0
  # wheel_radius_multiplier    : 1.0 # default: 1.0
  wheel_radius                : 0.036
  # wheel_separation            : 1.53
  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1   # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 2.0   # rad/s^2
