controllers:
  - name: 'TebLocalPlannerROS'
    type: 'teb_local_planner/TebLocalPlannerROS'
planners:
  - name: 'GlobalPlanner'
    type: 'global_planner/GlobalPlanner'
  
robot_base_frame: car_body
controller_frequency: 5.0
controller_patience: 15.0

planner_frequency: 1.0
planner_patience: 5.0

